<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitba8747839e72250266cb32f396d9dcf4
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'MyClub\\Sections\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'MyClub\\Sections\\' => 
        array (
	        0 => __DIR__ . '/../lib' . '/src',
        ),
    );

    public static $classMap = array (
	    'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitba8747839e72250266cb32f396d9dcf4::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitba8747839e72250266cb32f396d9dcf4::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitba8747839e72250266cb32f396d9dcf4::$classMap;

        }, null, ClassLoader::class);
    }
}
